/* eslint-disable react-refresh/only-export-components */

import React, { createContext, useState, useEffect, ReactNode } from "react";

export type Language = "fr" | "en";

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.about": "À propos",
    "nav.method": "Méthode",
    "nav.services": "Services",
    "nav.contact": "Contact",
    "nav.webDev": "Développement Web",
    "nav.marketing": "Marketing Digital",
    "nav.design": "Design Graphique",
    "nav.solutions": "Solutions Métiers",
    
    // Hero Section
    "hero.futureReady": "Future Ready",
    "hero.slogan.from": "De",
    "hero.slogan.zero": "Zéro",
    "hero.slogan.to": "au",
    "hero.slogan.zenith": "Zénith",
    "hero.subtitle": "Solutions digitales • Marketing • Design • Technologie",
    "hero.description": "Entreprise technologique spécialisée dans la digitalisation, la structuration numérique et la visibilité des organisations à travers l'Afrique et au-delà.",
    "hero.description.part1": "Propulser les marques grâce au",
    "hero.description.and": "et",
    "hero.cta.start": "Démarrer votre projet",
    "hero.cta.discover": "Découvrir nos services",
    "hero.feature.webDev": "Développement Web",
    "hero.feature.marketing": "Marketing Digital",
    "hero.feature.design": "Design Graphique",
    "hero.feature.solutions": "Solutions Métiers",
    
    // Index Page - About Preview
    "index.about.label": "À PROPOS",
    "index.about.title": "Votre Partenaire vers le",
    "index.about.titleHighlight": "Zénith Digital",
    "index.about.description": "ZENORA est une entreprise technologique spécialisée dans la digitalisation, la structuration numérique et la visibilité des organisations. Nous accompagnons entreprises et institutions dans leur transformation digitale.",
    "index.about.learnMore": "En savoir plus",
    "index.about.mission": "Mission",
    "index.about.missionDesc": "Technologie accessible",
    "index.about.vision": "Vision",
    "index.about.visionDesc": "Leader technologique",
    "index.about.value1": "Approche orientée résultats",
    "index.about.value2": "Transparence et communication",
    "index.about.value3": "Accompagnement personnalisé",
    
    // Index Page - Method Preview
    "index.method.label": "NOTRE MÉTHODE",
    "index.method.title": "Un Processus",
    "index.method.titleHighlight": "Structuré",
    "index.method.titleEnd": "en 5 Étapes",
    "index.method.description": "De l'analyse initiale au suivi post-lancement, nous garantissons transparence et excellence à chaque étape de votre projet.",
    "index.method.step1": "Analyse",
    "index.method.step2": "Solution",
    "index.method.step3": "Développement",
    "index.method.step4": "Déploiement",
    "index.method.step5": "Suivi",
    "index.method.discover": "Découvrir notre méthode",
    
    // Index Page - Contact CTA
    "index.contact.label": "CONTACT",
    "index.contact.title": "Prêt à Transformer Votre",
    "index.contact.titleHighlight": "Vision",
    "index.contact.description": "Discutons de votre projet et découvrez comment ZENORA peut vous accompagner dans votre transformation digitale.",
    "index.contact.cta": "Contactez-nous",
    "index.contact.services": "Voir nos services",
    
    // About Page
    "about.label": "À PROPOS DE ZENORA",
    "about.title": "Votre Partenaire vers le",
    "about.titleHighlight": "Zénith Digital",
    "about.description": "ZENORA est une entreprise technologique spécialisée dans la digitalisation, la structuration numérique et la visibilité des organisations à l'échelle internationale.",
    "about.presentation": "Présentation",
    "about.presentationHighlight": "Générale",
    "about.presentationText1": "accompagne entreprises, entrepreneurs et institutions à chaque étape de leur transformation digitale. Notre expertise couvre l'ensemble du spectre numérique, de la stratégie à l'exécution.",
    "about.presentationText2": "De la conception initiale jusqu'au déploiement de solutions numériques fiables, performantes et évolutives, ZENORA s'engage à proposer des outils adaptés aux réalités locales, conçus pour améliorer durablement l'efficacité, l'organisation et l'impact de ses partenaires.",
    "about.whatWeEnable": "Ce que ZENORA vous permet de faire",
    "about.benefit1": "Renforcer votre visibilité digitale",
    "about.benefit2": "Valoriser votre image de marque",
    "about.benefit3": "Structurer vos processus numériques",
    "about.benefit4": "Préparer la croissance de votre activité",
    "about.values": "Nos",
    "about.valuesHighlight": "Valeurs",
    "about.value.results": "Résultats",
    "about.value.resultsDesc": "Approche orientée performance et mesure d'impact",
    "about.value.transparency": "Transparence",
    "about.value.transparencyDesc": "Communication claire et continue à chaque étape",
    "about.value.innovation": "Innovation",
    "about.value.innovationDesc": "Solutions évolutives, modernes et avant-gardistes",
    "about.value.support": "Accompagnement",
    "about.value.supportDesc": "Support personnalisé et suivi dédié",
    "about.engagements": "Nos",
    "about.engagementsHighlight": "Engagements",
    "about.engagementsDesc": "Des principes fondamentaux qui guident chacune de nos interventions",
    "about.engagement.reliability": "Fiabilité",
    "about.engagement.reliabilityDesc": "Des solutions robustes et pérennes pour votre activité",
    "about.engagement.guidance": "Orientation",
    "about.engagement.guidanceDesc": "Un guidage stratégique adapté à vos objectifs",
    "about.engagement.responsiveness": "Réactivité",
    "about.engagement.responsivenessDesc": "Une équipe disponible et des délais maîtrisés",
    "about.engagement.excellence": "Excellence",
    "about.engagement.excellenceDesc": "Un niveau de qualité conforme aux standards internationaux",
    "about.reasonTitle": "Notre Raison",
    "about.reasonHighlight": "d'Être",
    "about.mission.title": "Notre Mission",
    "about.mission.text": "Rendre la technologie simple, puissante et accessible à toutes les organisations désireuses de se structurer, de rayonner et de s'imposer dans l'ère numérique.",
    "about.mission.point1": "Démocratiser l'accès aux outils numériques",
    "about.mission.point2": "Accompagner la croissance durable",
    "about.mission.point3": "Créer un impact mesurable",
    "about.vision.title": "Notre Vision",
    "about.vision.text": "Devenir un acteur technologique de référence à l'échelle internationale, reconnu pour l'excellence de ses solutions et l'impact de ses accompagnements.",
    "about.vision.point1": "Leadership technologique africain",
    "about.vision.point2": "Excellence et innovation continue",
    "about.vision.point3": "Partenariats stratégiques mondiaux",
    "about.imageAlt": "Équipe ZENORA au travail",
    "about.quote": "Zenora",
    "about.quoteText": ", de Zéro au Zénith",
    
    // Method Page
    "method.label": "NOTRE MÉTHODE",
    "method.title": "Un Processus",
    "method.titleHighlight": "Rigoureux",
    "method.titleEnd": "et Transparent",
    "method.description": "Une approche structurée en 5 étapes pour garantir le succès de votre projet, de l'analyse initiale jusqu'au suivi post-lancement.",
    "method.step1.title": "Analyse et Compréhension",
    "method.step1.description": "Nous étudions vos besoins, votre secteur et vos objectifs pour une compréhension approfondie de votre projet.",
    "method.step1.detail1": "Audit de l'existant",
    "method.step1.detail2": "Étude du marché cible",
    "method.step1.detail3": "Identification des objectifs clés",
    "method.step1.detail4": "Analyse de la concurrence",
    "method.step2.title": "Proposition de Solution Adaptée",
    "method.step2.description": "Nous élaborons une stratégie sur mesure et des solutions technologiques adaptées à votre réalité.",
    "method.step2.detail1": "Recommandations stratégiques",
    "method.step2.detail2": "Proposition technique détaillée",
    "method.step2.detail3": "Planning et jalons",
    "method.step2.detail4": "Budget transparent",
    "method.step3.title": "Conception et Développement",
    "method.step3.description": "Notre équipe conçoit et développe votre solution avec rigueur, en respectant les standards de qualité.",
    "method.step3.detail1": "Design UX/UI premium",
    "method.step3.detail2": "Développement agile",
    "method.step3.detail3": "Tests qualité continus",
    "method.step3.detail4": "Revues régulières",
    "method.step4.title": "Validation et Déploiement",
    "method.step4.description": "Tests approfondis, validation client et mise en production de votre solution dans les meilleures conditions.",
    "method.step4.detail1": "Tests d'acceptation",
    "method.step4.detail2": "Formation des équipes",
    "method.step4.detail3": "Mise en production",
    "method.step4.detail4": "Documentation complète",
    "method.step5.title": "Suivi, Support et Amélioration Continue",
    "method.step5.description": "Accompagnement post-lancement, maintenance et optimisations continues pour garantir la pérennité.",
    "method.step5.detail1": "Support technique dédié",
    "method.step5.detail2": "Maintenance préventive",
    "method.step5.detail3": "Évolutions régulières",
    "method.step5.detail4": "Rapports de performance",
    "method.trust.title": "Pourquoi nous faire confiance ?",
    "method.trust.point1": "Approche orientée résultats",
    "method.trust.point2": "Transparence et communication",
    "method.trust.point3": "Solutions claires et évolutives",
    "method.trust.point4": "Accompagnement personnalisé",
    "method.trust.cta": "Démarrer un projet",
    
    // Contact Page
    "contact.label": "CONTACTEZ-NOUS",
    "contact.title": "Parlons de Votre",
    "contact.titleHighlight": "Projet",
    "contact.description": "Prêt à transformer votre vision en réalité ? Notre équipe est à votre disposition pour discuter de vos besoins et vous accompagner dans votre transformation digitale.",
    "contact.availability": "Disponibilité",
    "contact.availabilityValue": "Lun - Ven, 8h - 18h",
    "contact.responseTime": "Réponse moyenne",
    "contact.responseTimeValue": "Sous 24 heures",
    "contact.reach": "Portée",
    "contact.reachValue": "Afrique & International",
    "contact.info.address": "Adresse",
    "contact.info.phone": "Téléphone",
    "contact.info.email": "Email",
    "contact.info.website": "Site Web",
    "contact.collab": "Chez ZENORA, la collaboration est au cœur de notre succès. Nous nous entourons des meilleurs talents et partenaires pour offrir des solutions innovantes et durables à nos clients.",
    "contact.followUs": "Suivez-nous sur les réseaux",
    "contact.form.title": "Envoyez-nous un message",
    "contact.form.name": "Nom complet",
    "contact.form.namePlaceholder": "Votre nom",
    "contact.form.email": "Adresse email",
    "contact.form.emailPlaceholder": "votre@email.com",
    "contact.form.phone": "Téléphone",
    "contact.form.phonePlaceholder": "+237 6XX XXX XXX",
    "contact.form.company": "Entreprise",
    "contact.form.companyPlaceholder": "Votre entreprise",
    "contact.form.subject": "Sujet",
    "contact.form.subjectPlaceholder": "L'objet de votre message",
    "contact.form.message": "Message",
    "contact.form.messagePlaceholder": "Décrivez votre projet ou votre demande...",
    "contact.form.submit": "Envoyer le message",
    "contact.form.submitting": "Envoi en cours...",
    "contact.form.success": "Message envoyé avec succès !",
    "contact.form.successDesc": "Nous vous répondrons dans les plus brefs délais.",
    "contact.whatsapp.title": "Préférez une discussion instantanée ?",
    "contact.whatsapp.description": "Échangeons directement sur WhatsApp pour discuter de votre projet, obtenir un devis rapide ou poser vos questions. Réponse garantie en moins d'une heure.",
    "contact.whatsapp.button": "Discuter sur WhatsApp",
    "contact.whatsapp.note": "Disponible du lundi au samedi • 8h - 20h (GMT+1)",
    
    // Services Page
    "services.label": "NOS SERVICES",
    "services.title": "Des solutions",
    "services.titleHighlight": "complètes",
    "services.titleEnd": "pour votre réussite",
    "services.description": "Nous accompagnons les organisations dans leur transformation digitale avec une approche sur mesure, alliant expertise technique et vision stratégique.",
    "services.learnMore": "En savoir plus",
    "services.cta.title": "Prêt à démarrer votre",
    "services.cta.titleHighlight": "projet",
    "services.cta.description": "Contactez-nous pour discuter de vos besoins et découvrir comment nous pouvons vous accompagner.",
    "services.cta.button": "Contactez-nous",
    
    "services.webDev.title": "Digitalisation & Développement Web",
    "services.webDev.description": "Nous concevons des solutions web sur mesure, pensées pour répondre à vos besoins actuels et évoluer avec votre activité.",
    "services.webDev.feature1": "Sites Web Vitrines Sécurisés",
    "services.webDev.feature2": "Applications Web Sur Mesure",
    "services.webDev.feature3": "Sites E-commerce",
    "services.webDev.feature4": "Portails Institutionnels",
    
    "services.marketing.title": "Marketing Digital & Croissance",
    "services.marketing.description": "Nous développons votre présence en ligne pour attirer, engager et convertir votre audience cible.",
    "services.marketing.feature1": "Social Media Marketing",
    "services.marketing.feature2": "Email Marketing & Newsletter",
    "services.marketing.feature3": "Référencement SEO & SEA",
    "services.marketing.feature4": "Publicité en Ligne",
    
    "services.design.title": "Graphic & Motion Design",
    "services.design.description": "Nous créons des supports visuels professionnels qui renforcent votre image et soutiennent vos actions commerciales.",
    "services.design.feature1": "Identité Visuelle & Logos",
    "services.design.feature2": "Production & Montage Vidéo",
    "services.design.feature3": "Cartes & Supports Institutionnels",
    "services.design.feature4": "Vidéos Publicitaires & Motion",
    
    "services.solutions.title": "Solutions Métiers & Expertises",
    "services.solutions.description": "Nous proposons des services transversaux pour renforcer la performance globale de votre organisation.",
    "services.solutions.feature1": "Intégration ERP & CRM",
    "services.solutions.feature2": "Configuration Odoo, SAGE, SAP",
    "services.solutions.feature3": "Gestion de Restaurants",
    "services.solutions.feature4": "Solutions Personnalisables",
    
    // Service Detail Pages - Common
    "serviceDetail.back": "Retour aux services",
    "serviceDetail.quote": "Demander un devis",
    "serviceDetail.solutions": "Nos Solutions",
    "serviceDetail.services": "Nos Services",
    "serviceDetail.creations": "Nos Créations",
    "serviceDetail.expertises": "Nos Expertises",
    "serviceDetail.whyChoose": "Pourquoi nous choisir ?",
    "serviceDetail.advantages": "Nos Avantages",
    "serviceDetail.approach": "Notre Approche",
    "serviceDetail.process": "Notre Processus",
    "serviceDetail.sectors": "Secteurs d'Intervention",
    "serviceDetail.contactUs": "Contactez-nous",
    
    // Web Development Page
    "webDev.label": "DÉVELOPPEMENT WEB",
    "webDev.title": "Digitalisation &",
    "webDev.titleHighlight": "Développement Web",
    "webDev.description": "Nous concevons des solutions web sur mesure, pensées pour répondre à vos besoins actuels et évoluer avec votre activité. De la conception à la mise en ligne, nous vous accompagnons à chaque étape.",
    "webDev.solutionsDesc": "Des solutions adaptées à chaque besoin, de la simple vitrine au système complexe",
    "webDev.service1.title": "Sites Web Vitrines",
    "webDev.service1.desc": "Des sites élégants et performants pour présenter votre activité de manière professionnelle.",
    "webDev.service2.title": "Applications Web Sur Mesure",
    "webDev.service2.desc": "Solutions personnalisées répondant parfaitement à vos processus métier spécifiques.",
    "webDev.service3.title": "Sites E-commerce",
    "webDev.service3.desc": "Boutiques en ligne optimisées pour la conversion et l'expérience utilisateur.",
    "webDev.service4.title": "Portails Institutionnels",
    "webDev.service4.desc": "Plateformes robustes pour institutions et grandes organisations.",
    "webDev.service5.title": "Plateformes E-learning",
    "webDev.service5.desc": "Solutions de formation en ligne interactives et engageantes.",
    "webDev.service6.title": "Solutions Métiers Adaptées",
    "webDev.service6.desc": "Applications sectorielles sur mesure pour répondre à vos défis uniques.",
    "webDev.advantage1.title": "Performance Optimale",
    "webDev.advantage1.desc": "Sites ultra-rapides avec les dernières technologies pour une expérience fluide.",
    "webDev.advantage2.title": "Sécurité Renforcée",
    "webDev.advantage2.desc": "Protection avancée de vos données et celles de vos utilisateurs.",
    "webDev.advantage3.title": "Support Continu",
    "webDev.advantage3.desc": "Accompagnement technique et maintenance pour assurer la pérennité de votre projet.",
    "webDev.process1": "Analyse",
    "webDev.process1.desc": "Étude approfondie de vos besoins",
    "webDev.process2": "Conception",
    "webDev.process2.desc": "Design et architecture technique",
    "webDev.process3": "Développement",
    "webDev.process3.desc": "Réalisation et tests rigoureux",
    "webDev.process4": "Déploiement",
    "webDev.process4.desc": "Mise en ligne et accompagnement",
    "webDev.cta.title": "Prêt à lancer votre",
    "webDev.cta.titleHighlight": "projet web",
    "webDev.cta.description": "Contactez-nous pour une consultation gratuite et découvrez comment nous pouvons transformer votre vision en réalité digitale.",
    
    // Marketing Digital Page
    "marketing.label": "MARKETING DIGITAL",
    "marketing.title": "Marketing Digital &",
    "marketing.titleHighlight": "Croissance",
    "marketing.description": "Nous développons votre présence en ligne pour attirer, engager et convertir votre audience. Notre approche data-driven garantit des résultats mesurables et un retour sur investissement optimal.",
    "marketing.servicesDesc": "Une gamme complète de services pour booster votre visibilité en ligne",
    "marketing.service1.title": "Social Media Marketing",
    "marketing.service1.desc": "Stratégies de contenu et gestion de communauté sur les réseaux sociaux.",
    "marketing.service2.title": "Email Marketing & Newsletter",
    "marketing.service2.desc": "Campagnes d'emailing ciblées pour fidéliser et convertir votre audience.",
    "marketing.service3.title": "Publicité en Ligne",
    "marketing.service3.desc": "Campagnes publicitaires Google Ads, Meta Ads et LinkedIn pour maximiser votre ROI.",
    "marketing.service4.title": "Création de Contenus",
    "marketing.service4.desc": "Stratégie éditoriale et production de contenus engageants et optimisés.",
    "marketing.service5.title": "Référencement SEO & SEA",
    "marketing.service5.desc": "Optimisation pour les moteurs de recherche et publicité payante ciblée.",
    "marketing.service6.title": "Stratégies & Reporting",
    "marketing.service6.desc": "Analyse de données et rapports détaillés pour optimiser vos performances.",
    "marketing.advantage1.title": "Ciblage Précis",
    "marketing.advantage1.desc": "Atteignez exactement votre audience cible avec des stratégies personnalisées.",
    "marketing.advantage2.title": "Croissance Mesurable",
    "marketing.advantage2.desc": "Des résultats concrets et mesurables grâce à nos outils d'analyse avancés.",
    "marketing.advantage3.title": "Engagement Renforcé",
    "marketing.advantage3.desc": "Créez des connexions authentiques avec votre communauté.",
    "marketing.cta.title": "Boostez votre",
    "marketing.cta.titleHighlight": "visibilité",
    "marketing.cta.description": "Contactez-nous pour une analyse gratuite de votre présence digitale et découvrez comment atteindre vos objectifs de croissance.",
    
    // Design Graphic Page
    "design.label": "DESIGN GRAPHIQUE",
    "design.title": "Graphic &",
    "design.titleHighlight": "Motion Design",
    "design.description": "Nous créons des supports visuels professionnels qui renforcent votre image et soutiennent vos actions commerciales. Du logo aux vidéos publicitaires, nous donnons vie à votre identité.",
    "design.creationsDesc": "Des solutions créatives pour tous vos besoins en communication visuelle",
    "design.service1.title": "Identité Visuelle & Logos",
    "design.service1.desc": "Création de logos et chartes graphiques qui reflètent l'essence de votre marque.",
    "design.service2.title": "Production & Montage Vidéo",
    "design.service2.desc": "Vidéos professionnelles pour captiver votre audience et raconter votre histoire.",
    "design.service3.title": "Cartes & Supports Institutionnels",
    "design.service3.desc": "Cartes de visite, papeterie et supports professionnels de haute qualité.",
    "design.service4.title": "Rollups, Banderoles & Panneaux",
    "design.service4.desc": "Signalétique et affichage grand format pour une visibilité maximale.",
    "design.service5.title": "Vidéos Publicitaires & Motion",
    "design.service5.desc": "Animations et vidéos motion design pour des campagnes percutantes.",
    "design.service6.title": "Flyers, Affiches & Dépliants",
    "design.service6.desc": "Supports de communication imprimés créatifs et impactants.",
    "design.advantage1.title": "Design Distinctif",
    "design.advantage1.desc": "Des créations uniques qui vous démarquent de la concurrence.",
    "design.advantage2.title": "Cohérence de Marque",
    "design.advantage2.desc": "Une identité visuelle harmonieuse sur tous vos supports.",
    "design.advantage3.title": "Créativité Sans Limites",
    "design.advantage3.desc": "Des designs innovants qui captivent et inspirent.",
    "design.cta.title": "Donnez vie à votre",
    "design.cta.titleHighlight": "image",
    "design.cta.description": "Contactez-nous pour discuter de votre projet créatif et découvrir comment nous pouvons sublimer votre marque.",
    
    // Solutions Métiers Page
    "solutions.label": "SOLUTIONS MÉTIERS",
    "solutions.title": "Solutions Métiers &",
    "solutions.titleHighlight": "Expertises",
    "solutions.description": "Nous proposons des services transversaux pour renforcer la performance globale de votre organisation. Des solutions ERP aux logiciels sectoriels, nous optimisons vos processus métier.",
    "solutions.expertisesDesc": "Des solutions logicielles adaptées à chaque secteur d'activité",
    "solutions.service1.title": "Intégration ERP & CRM",
    "solutions.service1.desc": "Mise en place de systèmes intégrés pour optimiser vos processus métier.",
    "solutions.service2.title": "Configuration Odoo, SAGE, SAP",
    "solutions.service2.desc": "Paramétrage et personnalisation des principaux ERP du marché.",
    "solutions.service3.title": "Gestion de Restaurants",
    "solutions.service3.desc": "Solutions complètes pour la restauration : caisse, stocks, commandes.",
    "solutions.service4.title": "Gestion de Salons de Coiffure",
    "solutions.service4.desc": "Logiciels de gestion adaptés aux métiers de la beauté et du bien-être.",
    "solutions.service5.title": "Gestion d'Écoles",
    "solutions.service5.desc": "Plateformes de gestion scolaire pour établissements éducatifs.",
    "solutions.service6.title": "Solutions Personnalisables",
    "solutions.service6.desc": "Développement sur mesure pour répondre à vos besoins spécifiques.",
    "solutions.advantage1.title": "Sur Mesure",
    "solutions.advantage1.desc": "Des solutions adaptées précisément à vos processus et contraintes métier.",
    "solutions.advantage2.title": "Données Centralisées",
    "solutions.advantage2.desc": "Une vision unifiée de vos données pour des décisions éclairées.",
    "solutions.advantage3.title": "Performance Accrue",
    "solutions.advantage3.desc": "Automatisation et optimisation pour une productivité maximale.",
    "solutions.sector1": "Restauration",
    "solutions.sector2": "Éducation",
    "solutions.sector3": "Santé",
    "solutions.sector4": "Commerce",
    "solutions.sector5": "Industrie",
    "solutions.sector6": "Services",
    "solutions.sector7": "Beauté & Bien-être",
    "solutions.sector8": "Immobilier",
    "solutions.cta.title": "Optimisez vos",
    "solutions.cta.titleHighlight": "processus",
    "solutions.cta.description": "Contactez-nous pour un audit gratuit de vos besoins et découvrir comment nos solutions peuvent transformer votre activité.",
    
    // Footer
    "footer.navigation": "Navigation",
    "footer.services": "Services",
    "footer.contact": "Contact",
    "footer.rights": "Tous droits réservés.",
    "footer.privacy": "Politique de confidentialité",
    "footer.legal": "Mentions légales",
    "footer.backToTop": "Retour en haut",
    "footer.slogan.from": "De",
    "footer.slogan.zero": "Zéro",
    "footer.slogan.to": "au",
    "footer.slogan.zenith": "Zénith",
    "footer.description": "Entreprise technologique spécialisée dans la digitalisation et la visibilité des organisations en Afrique.",
    
    // Blog
    "nav.blog": "Blog",
    "blog.label": "BLOG",
    "blog.title": "Nos",
    "blog.titleHighlight": "Insights",
    "blog.description": "Découvrez nos derniers articles sur le digital, le marketing, le design et les solutions métiers.",
    "blog.seo.title": "Blog - Insights Digital",
    "blog.seo.description": "Découvrez nos articles et conseils sur la transformation digitale, le marketing et le design.",
    "blog.searchPlaceholder": "Rechercher un article...",
    "blog.loadMore": "Charger plus d'articles",
    "blog.loading": "Chargement...",
    "blog.noResults": "Aucun article trouvé",
    "blog.noResultsDesc": "Essayez de modifier vos critères de recherche.",
    "blog.offline": "Vous êtes hors ligne",
    "blog.slowConnection": "Connexion lente détectée",
    "blog.loadingArticle": "Chargement de l'article...",
    "blog.notFound": "Article non trouvé",
    "blog.notFoundDesc": "L'article que vous cherchez n'existe pas ou a été supprimé.",
    "blog.backToList": "Retour au blog",
    "blog.share": "Partager",
    "blog.cta.title": "Besoin d'un accompagnement ?",
    "blog.cta.description": "Contactez-nous pour discuter de votre projet de transformation digitale.",
    "blog.cta.button": "Nous contacter",
    
    // Admin
    "admin.nav.dashboard": "Tableau de bord",
    "admin.nav.blogs": "Articles",
    "admin.nav.newBlog": "Nouvel article",
    "admin.nav.settings": "Paramètres",
    "admin.logout": "Déconnexion",
    "admin.dashboard.title": "Tableau de bord",
    "admin.dashboard.subtitle": "Gérez votre contenu et suivez vos performances",
    "admin.dashboard.newPost": "Nouvel article",
    "admin.dashboard.recentPosts": "Articles récents",
    "admin.dashboard.viewAll": "Voir tout",
    "admin.dashboard.noPosts": "Aucun article pour le moment",
    "admin.stats.totalPosts": "Total articles",
    "admin.stats.published": "Publiés",
    "admin.stats.drafts": "Brouillons",
    "admin.stats.views": "Vues totales",
    "admin.status.published": "Publié",
    "admin.status.draft": "Brouillon",
    "admin.blogs.title": "Gestion des articles",
    "admin.blogs.subtitle": "Tous vos articles",
    "admin.blogs.newPost": "Nouvel article",
    "admin.blogs.searchPlaceholder": "Rechercher...",
    "admin.blogs.table.title": "Titre",
    "admin.blogs.table.category": "Catégorie",
    "admin.blogs.table.date": "Date",
    "admin.blogs.table.status": "Statut",
    "admin.blogs.table.actions": "Actions",
    "admin.blogs.noPosts": "Aucun article",
    "admin.blogs.noResults": "Aucun résultat",
    "admin.actions.view": "Voir",
    "admin.actions.edit": "Modifier",
    "admin.actions.delete": "Supprimer",
    "admin.actions.publish": "Publier",
    "admin.actions.unpublish": "Dépublier",
    "admin.dialog.deleteTitle": "Supprimer l'article ?",
    "admin.dialog.deleteDescription": "Cette action est irréversible. L'article sera définitivement supprimé.",
    "admin.dialog.cancel": "Annuler",
    "admin.dialog.delete": "Supprimer",
    "admin.toast.deleted": "Article supprimé",
    "admin.toast.published": "Article publié",
    "admin.toast.unpublished": "Article dépublié",
    "admin.toast.created": "Article créé",
    "admin.toast.updated": "Article mis à jour",
    "admin.toast.error": "Une erreur est survenue",
    "admin.editor.newTitle": "Nouvel article",
    "admin.editor.editTitle": "Modifier l'article",
    "admin.editor.subtitle": "Remplissez les informations ci-dessous",
    "admin.editor.save": "Enregistrer",
    "admin.editor.title": "Titre",
    "admin.editor.titlePlaceholder": "Titre de l'article...",
    "admin.editor.excerpt": "Extrait",
    "admin.editor.excerptPlaceholder": "Courte description de l'article...",
    "admin.editor.content": "Contenu",
    "admin.editor.contentPlaceholder": "Contenu de l'article (HTML supporté)...",
    "admin.editor.htmlSupported": "Le HTML est supporté pour le formatage.",
    "admin.editor.coverImage": "Image de couverture",
    "admin.editor.category": "Catégorie",
    "admin.editor.tags": "Tags",
    "admin.editor.tagsPlaceholder": "tag1, tag2, tag3",
    "admin.editor.preview": "Aperçu",
    "admin.editor.requiredFields": "Veuillez remplir tous les champs obligatoires",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About",
    "nav.method": "Method",
    "nav.services": "Services",
    "nav.contact": "Contact",
    "nav.webDev": "Web Development",
    "nav.marketing": "Digital Marketing",
    "nav.design": "Graphic Design",
    "nav.solutions": "Business Solutions",
    
    // Hero Section
    "hero.futureReady": "Future Ready",
    "hero.slogan.from": "From",
    "hero.slogan.zero": "Zero",
    "hero.slogan.to": "to",
    "hero.slogan.zenith": "Zenith",
    "hero.subtitle": "Digital solutions • Marketing • Design • Technology",
    "hero.description": "Technology company specialized in digitalization, digital structuring and visibility of organizations across Africa and beyond.",
    "hero.description.part1": "Propelling brands through",
    "hero.description.and": "and",
    "hero.cta.start": "Start your project",
    "hero.cta.discover": "Discover our services",
    "hero.feature.webDev": "Web Development",
    "hero.feature.marketing": "Digital Marketing",
    "hero.feature.design": "Graphic Design",
    "hero.feature.solutions": "Business Solutions",
    
    // Index Page - About Preview
    "index.about.label": "ABOUT",
    "index.about.title": "Your Partner towards the",
    "index.about.titleHighlight": "Digital Zenith",
    "index.about.description": "ZENORA is a technology company specialized in digitalization, digital structuring and visibility of organizations. We support businesses and institutions in their digital transformation.",
    "index.about.learnMore": "Learn more",
    "index.about.mission": "Mission",
    "index.about.missionDesc": "Accessible technology",
    "index.about.vision": "Vision",
    "index.about.visionDesc": "Technology leader",
    "index.about.value1": "Results-oriented approach",
    "index.about.value2": "Transparency and communication",
    "index.about.value3": "Personalized support",
    
    // Index Page - Method Preview
    "index.method.label": "OUR METHOD",
    "index.method.title": "A",
    "index.method.titleHighlight": "Structured",
    "index.method.titleEnd": "Process in 5 Steps",
    "index.method.description": "From initial analysis to post-launch follow-up, we guarantee transparency and excellence at every stage of your project.",
    "index.method.step1": "Analysis",
    "index.method.step2": "Solution",
    "index.method.step3": "Development",
    "index.method.step4": "Deployment",
    "index.method.step5": "Follow-up",
    "index.method.discover": "Discover our method",
    
    // Index Page - Contact CTA
    "index.contact.label": "CONTACT",
    "index.contact.title": "Ready to Transform Your",
    "index.contact.titleHighlight": "Vision",
    "index.contact.description": "Let's discuss your project and discover how ZENORA can support you in your digital transformation.",
    "index.contact.cta": "Contact us",
    "index.contact.services": "View our services",
    
    // About Page
    "about.label": "ABOUT ZENORA",
    "about.title": "Your Partner towards the",
    "about.titleHighlight": "Digital Zenith",
    "about.description": "ZENORA is a technology company specialized in digitalization, digital structuring and visibility of organizations on an international scale.",
    "about.presentation": "General",
    "about.presentationHighlight": "Presentation",
    "about.presentationText1": "supports companies, entrepreneurs and institutions at every stage of their digital transformation. Our expertise covers the entire digital spectrum, from strategy to execution.",
    "about.presentationText2": "From initial design to the deployment of reliable, high-performance and scalable digital solutions, ZENORA is committed to offering tools adapted to local realities, designed to sustainably improve the efficiency, organization and impact of its partners.",
    "about.whatWeEnable": "What ZENORA enables you to do",
    "about.benefit1": "Strengthen your digital visibility",
    "about.benefit2": "Enhance your brand image",
    "about.benefit3": "Structure your digital processes",
    "about.benefit4": "Prepare for business growth",
    "about.values": "Our",
    "about.valuesHighlight": "Values",
    "about.value.results": "Results",
    "about.value.resultsDesc": "Performance-oriented approach and impact measurement",
    "about.value.transparency": "Transparency",
    "about.value.transparencyDesc": "Clear and continuous communication at every stage",
    "about.value.innovation": "Innovation",
    "about.value.innovationDesc": "Scalable, modern and cutting-edge solutions",
    "about.value.support": "Support",
    "about.value.supportDesc": "Personalized support and dedicated follow-up",
    "about.engagements": "Our",
    "about.engagementsHighlight": "Commitments",
    "about.engagementsDesc": "Fundamental principles that guide each of our interventions",
    "about.engagement.reliability": "Reliability",
    "about.engagement.reliabilityDesc": "Robust and sustainable solutions for your business",
    "about.engagement.guidance": "Guidance",
    "about.engagement.guidanceDesc": "Strategic guidance adapted to your objectives",
    "about.engagement.responsiveness": "Responsiveness",
    "about.engagement.responsivenessDesc": "An available team and controlled deadlines",
    "about.engagement.excellence": "Excellence",
    "about.engagement.excellenceDesc": "A level of quality in line with international standards",
    "about.reasonTitle": "Our Reason",
    "about.reasonHighlight": "for Being",
    "about.mission.title": "Our Mission",
    "about.mission.text": "Make technology simple, powerful and accessible to all organizations wishing to structure themselves, shine and establish themselves in the digital era.",
    "about.mission.point1": "Democratize access to digital tools",
    "about.mission.point2": "Support sustainable growth",
    "about.mission.point3": "Create measurable impact",
    "about.vision.title": "Our Vision",
    "about.vision.text": "Become a leading technology player on an international scale, recognized for the excellence of its solutions and the impact of its support.",
    "about.vision.point1": "African technology leadership",
    "about.vision.point2": "Continuous excellence and innovation",
    "about.vision.point3": "Global strategic partnerships",
    "about.imageAlt": "ZENORA team at work",
    "about.quote": "Zenora",
    "about.quoteText": ", from Zero to Zenith",
    
    // Method Page
    "method.label": "OUR METHOD",
    "method.title": "A",
    "method.titleHighlight": "Rigorous",
    "method.titleEnd": "and Transparent Process",
    "method.description": "A structured approach in 5 steps to guarantee the success of your project, from initial analysis to post-launch follow-up.",
    "method.step1.title": "Analysis and Understanding",
    "method.step1.description": "We study your needs, your sector and your objectives for an in-depth understanding of your project.",
    "method.step1.detail1": "Existing audit",
    "method.step1.detail2": "Target market study",
    "method.step1.detail3": "Key objectives identification",
    "method.step1.detail4": "Competition analysis",
    "method.step2.title": "Tailored Solution Proposal",
    "method.step2.description": "We develop a tailor-made strategy and technological solutions adapted to your reality.",
    "method.step2.detail1": "Strategic recommendations",
    "method.step2.detail2": "Detailed technical proposal",
    "method.step2.detail3": "Planning and milestones",
    "method.step2.detail4": "Transparent budget",
    "method.step3.title": "Design and Development",
    "method.step3.description": "Our team designs and develops your solution with rigor, respecting quality standards.",
    "method.step3.detail1": "Premium UX/UI design",
    "method.step3.detail2": "Agile development",
    "method.step3.detail3": "Continuous quality tests",
    "method.step3.detail4": "Regular reviews",
    "method.step4.title": "Validation and Deployment",
    "method.step4.description": "In-depth testing, client validation and production launch of your solution in the best conditions.",
    "method.step4.detail1": "Acceptance tests",
    "method.step4.detail2": "Team training",
    "method.step4.detail3": "Production launch",
    "method.step4.detail4": "Complete documentation",
    "method.step5.title": "Follow-up, Support and Continuous Improvement",
    "method.step5.description": "Post-launch support, maintenance and continuous optimizations to ensure sustainability.",
    "method.step5.detail1": "Dedicated technical support",
    "method.step5.detail2": "Preventive maintenance",
    "method.step5.detail3": "Regular updates",
    "method.step5.detail4": "Performance reports",
    "method.trust.title": "Why trust us?",
    "method.trust.point1": "Results-oriented approach",
    "method.trust.point2": "Transparency and communication",
    "method.trust.point3": "Clear and scalable solutions",
    "method.trust.point4": "Personalized support",
    "method.trust.cta": "Start a project",
    
    // Contact Page
    "contact.label": "CONTACT US",
    "contact.title": "Let's Talk About Your",
    "contact.titleHighlight": "Project",
    "contact.description": "Ready to turn your vision into reality? Our team is at your disposal to discuss your needs and support you in your digital transformation.",
    "contact.availability": "Availability",
    "contact.availabilityValue": "Mon - Fri, 8am - 6pm",
    "contact.responseTime": "Average response",
    "contact.responseTimeValue": "Within 24 hours",
    "contact.reach": "Reach",
    "contact.reachValue": "Africa & International",
    "contact.info.address": "Address",
    "contact.info.phone": "Phone",
    "contact.info.email": "Email",
    "contact.info.website": "Website",
    "contact.collab": "At ZENORA, collaboration is at the heart of our success. We surround ourselves with the best talents and partners to offer innovative and sustainable solutions to our clients.",
    "contact.followUs": "Follow us on social media",
    "contact.form.title": "Send us a message",
    "contact.form.name": "Full name",
    "contact.form.namePlaceholder": "Your name",
    "contact.form.email": "Email address",
    "contact.form.emailPlaceholder": "your@email.com",
    "contact.form.phone": "Phone",
    "contact.form.phonePlaceholder": "+237 6XX XXX XXX",
    "contact.form.company": "Company",
    "contact.form.companyPlaceholder": "Your company",
    "contact.form.subject": "Subject",
    "contact.form.subjectPlaceholder": "The subject of your message",
    "contact.form.message": "Message",
    "contact.form.messagePlaceholder": "Describe your project or request...",
    "contact.form.submit": "Send message",
    "contact.form.submitting": "Sending...",
    "contact.form.success": "Message sent successfully!",
    "contact.form.successDesc": "We will respond as soon as possible.",
    "contact.whatsapp.title": "Prefer an instant conversation?",
    "contact.whatsapp.description": "Let's chat directly on WhatsApp to discuss your project, get a quick quote, or ask your questions. Response guaranteed within one hour.",
    "contact.whatsapp.button": "Chat on WhatsApp",
    "contact.whatsapp.note": "Available Monday to Saturday • 8am - 8pm (GMT+1)",
    
    // Services Page
    "services.label": "OUR SERVICES",
    "services.title": "Complete",
    "services.titleHighlight": "solutions",
    "services.titleEnd": "for your success",
    "services.description": "We support organizations in their digital transformation with a tailor-made approach, combining technical expertise and strategic vision.",
    "services.learnMore": "Learn more",
    "services.cta.title": "Ready to start your",
    "services.cta.titleHighlight": "project",
    "services.cta.description": "Contact us to discuss your needs and discover how we can support you.",
    "services.cta.button": "Contact us",
    
    "services.webDev.title": "Digitalization & Web Development",
    "services.webDev.description": "We design tailor-made web solutions, designed to meet your current needs and evolve with your business.",
    "services.webDev.feature1": "Secure Showcase Websites",
    "services.webDev.feature2": "Custom Web Applications",
    "services.webDev.feature3": "E-commerce Sites",
    "services.webDev.feature4": "Institutional Portals",
    
    "services.marketing.title": "Digital Marketing & Growth",
    "services.marketing.description": "We develop your online presence to attract, engage and convert your target audience.",
    "services.marketing.feature1": "Social Media Marketing",
    "services.marketing.feature2": "Email Marketing & Newsletter",
    "services.marketing.feature3": "SEO & SEA",
    "services.marketing.feature4": "Online Advertising",
    
    "services.design.title": "Graphic & Motion Design",
    "services.design.description": "We create professional visual materials that strengthen your image and support your commercial actions.",
    "services.design.feature1": "Visual Identity & Logos",
    "services.design.feature2": "Video Production & Editing",
    "services.design.feature3": "Business Cards & Institutional Materials",
    "services.design.feature4": "Advertising Videos & Motion",
    
    "services.solutions.title": "Business Solutions & Expertise",
    "services.solutions.description": "We offer cross-functional services to strengthen the overall performance of your organization.",
    "services.solutions.feature1": "ERP & CRM Integration",
    "services.solutions.feature2": "Odoo, SAGE, SAP Configuration",
    "services.solutions.feature3": "Restaurant Management",
    "services.solutions.feature4": "Customizable Solutions",
    
    // Service Detail Pages - Common
    "serviceDetail.back": "Back to services",
    "serviceDetail.quote": "Request a quote",
    "serviceDetail.solutions": "Our Solutions",
    "serviceDetail.services": "Our Services",
    "serviceDetail.creations": "Our Creations",
    "serviceDetail.expertises": "Our Expertise",
    "serviceDetail.whyChoose": "Why choose us?",
    "serviceDetail.advantages": "Our Advantages",
    "serviceDetail.approach": "Our Approach",
    "serviceDetail.process": "Our Process",
    "serviceDetail.sectors": "Sectors of Intervention",
    "serviceDetail.contactUs": "Contact us",
    
    // Web Development Page
    "webDev.label": "WEB DEVELOPMENT",
    "webDev.title": "Digitalization &",
    "webDev.titleHighlight": "Web Development",
    "webDev.description": "We design tailor-made web solutions, designed to meet your current needs and evolve with your business. From design to launch, we support you every step of the way.",
    "webDev.solutionsDesc": "Solutions adapted to every need, from simple showcase to complex system",
    "webDev.service1.title": "Showcase Websites",
    "webDev.service1.desc": "Elegant and high-performance sites to present your business professionally.",
    "webDev.service2.title": "Custom Web Applications",
    "webDev.service2.desc": "Customized solutions perfectly meeting your specific business processes.",
    "webDev.service3.title": "E-commerce Sites",
    "webDev.service3.desc": "Online stores optimized for conversion and user experience.",
    "webDev.service4.title": "Institutional Portals",
    "webDev.service4.desc": "Robust platforms for institutions and large organizations.",
    "webDev.service5.title": "E-learning Platforms",
    "webDev.service5.desc": "Interactive and engaging online training solutions.",
    "webDev.service6.title": "Tailored Business Solutions",
    "webDev.service6.desc": "Custom sector applications to meet your unique challenges.",
    "webDev.advantage1.title": "Optimal Performance",
    "webDev.advantage1.desc": "Ultra-fast sites with the latest technologies for a smooth experience.",
    "webDev.advantage2.title": "Enhanced Security",
    "webDev.advantage2.desc": "Advanced protection of your data and that of your users.",
    "webDev.advantage3.title": "Continuous Support",
    "webDev.advantage3.desc": "Technical support and maintenance to ensure the longevity of your project.",
    "webDev.process1": "Analysis",
    "webDev.process1.desc": "In-depth study of your needs",
    "webDev.process2": "Design",
    "webDev.process2.desc": "Design and technical architecture",
    "webDev.process3": "Development",
    "webDev.process3.desc": "Implementation and rigorous testing",
    "webDev.process4": "Deployment",
    "webDev.process4.desc": "Launch and support",
    "webDev.cta.title": "Ready to launch your",
    "webDev.cta.titleHighlight": "web project",
    "webDev.cta.description": "Contact us for a free consultation and discover how we can transform your vision into digital reality.",
    
    // Marketing Digital Page
    "marketing.label": "DIGITAL MARKETING",
    "marketing.title": "Digital Marketing &",
    "marketing.titleHighlight": "Growth",
    "marketing.description": "We develop your online presence to attract, engage and convert your audience. Our data-driven approach guarantees measurable results and optimal return on investment.",
    "marketing.servicesDesc": "A complete range of services to boost your online visibility",
    "marketing.service1.title": "Social Media Marketing",
    "marketing.service1.desc": "Content strategies and community management on social networks.",
    "marketing.service2.title": "Email Marketing & Newsletter",
    "marketing.service2.desc": "Targeted email campaigns to retain and convert your audience.",
    "marketing.service3.title": "Online Advertising",
    "marketing.service3.desc": "Google Ads, Meta Ads and LinkedIn advertising campaigns to maximize your ROI.",
    "marketing.service4.title": "Content Creation",
    "marketing.service4.desc": "Editorial strategy and production of engaging, optimized content.",
    "marketing.service5.title": "SEO & SEA",
    "marketing.service5.desc": "Search engine optimization and targeted paid advertising.",
    "marketing.service6.title": "Strategy & Reporting",
    "marketing.service6.desc": "Data analysis and detailed reports to optimize your performance.",
    "marketing.advantage1.title": "Precise Targeting",
    "marketing.advantage1.desc": "Reach exactly your target audience with personalized strategies.",
    "marketing.advantage2.title": "Measurable Growth",
    "marketing.advantage2.desc": "Concrete and measurable results thanks to our advanced analysis tools.",
    "marketing.advantage3.title": "Enhanced Engagement",
    "marketing.advantage3.desc": "Create authentic connections with your community.",
    "marketing.cta.title": "Boost your",
    "marketing.cta.titleHighlight": "visibility",
    "marketing.cta.description": "Contact us for a free analysis of your digital presence and discover how to achieve your growth objectives.",
    
    // Design Graphic Page
    "design.label": "GRAPHIC DESIGN",
    "design.title": "Graphic &",
    "design.titleHighlight": "Motion Design",
    "design.description": "We create professional visual materials that strengthen your image and support your commercial actions. From logos to advertising videos, we bring your identity to life.",
    "design.creationsDesc": "Creative solutions for all your visual communication needs",
    "design.service1.title": "Visual Identity & Logos",
    "design.service1.desc": "Logo and graphic charter creation that reflects the essence of your brand.",
    "design.service2.title": "Video Production & Editing",
    "design.service2.desc": "Professional videos to captivate your audience and tell your story.",
    "design.service3.title": "Business Cards & Institutional Materials",
    "design.service3.desc": "Business cards, stationery and high-quality professional materials.",
    "design.service4.title": "Rollups, Banners & Signs",
    "design.service4.desc": "Signage and large format display for maximum visibility.",
    "design.service5.title": "Advertising Videos & Motion",
    "design.service5.desc": "Animations and motion design videos for impactful campaigns.",
    "design.service6.title": "Flyers, Posters & Brochures",
    "design.service6.desc": "Creative and impactful printed communication materials.",
    "design.advantage1.title": "Distinctive Design",
    "design.advantage1.desc": "Unique creations that set you apart from the competition.",
    "design.advantage2.title": "Brand Consistency",
    "design.advantage2.desc": "A harmonious visual identity across all your media.",
    "design.advantage3.title": "Unlimited Creativity",
    "design.advantage3.desc": "Innovative designs that captivate and inspire.",
    "design.cta.title": "Bring your",
    "design.cta.titleHighlight": "image",
    "design.cta.description": "Contact us to discuss your creative project and discover how we can elevate your brand.",
    
    // Solutions Métiers Page
    "solutions.label": "BUSINESS SOLUTIONS",
    "solutions.title": "Business Solutions &",
    "solutions.titleHighlight": "Expertise",
    "solutions.description": "We offer cross-functional services to strengthen the overall performance of your organization. From ERP solutions to sector-specific software, we optimize your business processes.",
    "solutions.expertisesDesc": "Software solutions adapted to each sector of activity",
    "solutions.service1.title": "ERP & CRM Integration",
    "solutions.service1.desc": "Implementation of integrated systems to optimize your business processes.",
    "solutions.service2.title": "Odoo, SAGE, SAP Configuration",
    "solutions.service2.desc": "Setup and customization of the main ERPs on the market.",
    "solutions.service3.title": "Restaurant Management",
    "solutions.service3.desc": "Complete solutions for restaurants: POS, inventory, orders.",
    "solutions.service4.title": "Hair Salon Management",
    "solutions.service4.desc": "Management software adapted to beauty and wellness professions.",
    "solutions.service5.title": "School Management",
    "solutions.service5.desc": "School management platforms for educational institutions.",
    "solutions.service6.title": "Customizable Solutions",
    "solutions.service6.desc": "Tailor-made development to meet your specific needs.",
    "solutions.advantage1.title": "Tailor-Made",
    "solutions.advantage1.desc": "Solutions precisely adapted to your processes and business constraints.",
    "solutions.advantage2.title": "Centralized Data",
    "solutions.advantage2.desc": "A unified view of your data for informed decisions.",
    "solutions.advantage3.title": "Increased Performance",
    "solutions.advantage3.desc": "Automation and optimization for maximum productivity.",
    "solutions.sector1": "Restaurant",
    "solutions.sector2": "Education",
    "solutions.sector3": "Healthcare",
    "solutions.sector4": "Retail",
    "solutions.sector5": "Industry",
    "solutions.sector6": "Services",
    "solutions.sector7": "Beauty & Wellness",
    "solutions.sector8": "Real Estate",
    "solutions.cta.title": "Optimize your",
    "solutions.cta.titleHighlight": "processes",
    "solutions.cta.description": "Contact us for a free audit of your needs and discover how our solutions can transform your business.",
    
    // Footer
    "footer.navigation": "Navigation",
    "footer.services": "Services",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.legal": "Legal Mentions",
    "footer.backToTop": "Back to top",
    "footer.slogan.from": "From",
    "footer.slogan.zero": "Zero",
    "footer.slogan.to": "to",
    "footer.slogan.zenith": "Zenith",
    "footer.description": "Technology company specialized in digitalization and visibility of organizations in Africa.",
    
    // Blog
    "nav.blog": "Blog",
    "blog.label": "BLOG",
    "blog.title": "Our",
    "blog.titleHighlight": "Insights",
    "blog.description": "Discover our latest articles on digital, marketing, design and business solutions.",
    "blog.seo.title": "Blog - Digital Insights",
    "blog.seo.description": "Discover our articles and tips on digital transformation, marketing and design.",
    "blog.searchPlaceholder": "Search an article...",
    "blog.loadMore": "Load more articles",
    "blog.loading": "Loading...",
    "blog.noResults": "No articles found",
    "blog.noResultsDesc": "Try changing your search criteria.",
    "blog.offline": "You are offline",
    "blog.slowConnection": "Slow connection detected",
    "blog.loadingArticle": "Loading article...",
    "blog.notFound": "Article not found",
    "blog.notFoundDesc": "The article you are looking for does not exist or has been removed.",
    "blog.backToList": "Back to blog",
    "blog.share": "Share",
    "blog.cta.title": "Need support?",
    "blog.cta.description": "Contact us to discuss your digital transformation project.",
    "blog.cta.button": "Contact us",
    
    // Admin
    "admin.nav.dashboard": "Dashboard",
    "admin.nav.blogs": "Articles",
    "admin.nav.newBlog": "New article",
    "admin.nav.settings": "Settings",
    "admin.logout": "Logout",
    "admin.dashboard.title": "Dashboard",
    "admin.dashboard.subtitle": "Manage your content and track your performance",
    "admin.dashboard.newPost": "New article",
    "admin.dashboard.recentPosts": "Recent articles",
    "admin.dashboard.viewAll": "View all",
    "admin.dashboard.noPosts": "No articles yet",
    "admin.stats.totalPosts": "Total articles",
    "admin.stats.published": "Published",
    "admin.stats.drafts": "Drafts",
    "admin.stats.views": "Total views",
    "admin.status.published": "Published",
    "admin.status.draft": "Draft",
    "admin.blogs.title": "Article management",
    "admin.blogs.subtitle": "All your articles",
    "admin.blogs.newPost": "New article",
    "admin.blogs.searchPlaceholder": "Search...",
    "admin.blogs.table.title": "Title",
    "admin.blogs.table.category": "Category",
    "admin.blogs.table.date": "Date",
    "admin.blogs.table.status": "Status",
    "admin.blogs.table.actions": "Actions",
    "admin.blogs.noPosts": "No articles",
    "admin.blogs.noResults": "No results",
    "admin.actions.view": "View",
    "admin.actions.edit": "Edit",
    "admin.actions.delete": "Delete",
    "admin.actions.publish": "Publish",
    "admin.actions.unpublish": "Unpublish",
    "admin.dialog.deleteTitle": "Delete article?",
    "admin.dialog.deleteDescription": "This action is irreversible. The article will be permanently deleted.",
    "admin.dialog.cancel": "Cancel",
    "admin.dialog.delete": "Delete",
    "admin.toast.deleted": "Article deleted",
    "admin.toast.published": "Article published",
    "admin.toast.unpublished": "Article unpublished",
    "admin.toast.created": "Article created",
    "admin.toast.updated": "Article updated",
    "admin.toast.error": "An error occurred",
    "admin.editor.newTitle": "New article",
    "admin.editor.editTitle": "Edit article",
    "admin.editor.subtitle": "Fill in the information below",
    "admin.editor.save": "Save",
    "admin.editor.title": "Title",
    "admin.editor.titlePlaceholder": "Article title...",
    "admin.editor.excerpt": "Excerpt",
    "admin.editor.excerptPlaceholder": "Short description of the article...",
    "admin.editor.content": "Content",
    "admin.editor.contentPlaceholder": "Article content (HTML supported)...",
    "admin.editor.htmlSupported": "HTML is supported for formatting.",
    "admin.editor.coverImage": "Cover image",
    "admin.editor.category": "Category",
    "admin.editor.tags": "Tags",
    "admin.editor.tagsPlaceholder": "tag1, tag2, tag3",
    "admin.editor.preview": "Preview",
    "admin.editor.requiredFields": "Please fill in all required fields",
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("zenora-language");
    return (saved as Language) || "fr";
  });

  useEffect(() => {
    localStorage.setItem("zenora-language", language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const currentTranslations = translations[language];
    return (currentTranslations as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// `useLanguage` hook is defined in `./useLanguage` to satisfy react-refresh rules.
